# Generated by Django 5.2.17 on 2026-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('budget', models.CharField(blank=True, choices=[('under_2k', 'Under €2,000'), ('2k_5k', '€2,000 – €5,000'), ('5k_10k', '€5,000 – €10,000'), ('over_10k', 'Over €10,000'), ('not_sure', 'Not sure yet')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
