# Generated by Django 5.2.17 on 2026-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(default='Websites, online stores, bots and SaaS, built end to end', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subheadline',
            field=models.CharField(blank=True, default='Company sites, shops, custom features, website chatbots, Telegram bots and SaaS platforms, from simple to advanced.', max_length=300),
        ),
    ]
