# Generated by Django 5.2.17 on 2026-10-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_hero_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_photo',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
    ]
