# Generated by Django 5.2.17 on 2026-10-09 10:16

import apps.blog.content
from django.db import migrations, models


def _text(value):
    return [{"type": "text", "text": value}] if value else []


def _paragraphs(text):
    """Old text blocks: blank line = new paragraph, single newline = line break."""
    nodes = []
    for chunk in text.replace("\r\n", "\n").split("\n\n"):
        content = []
        for i, line in enumerate(chunk.strip("\n").split("\n")):
            if i and content:
                content.append({"type": "hardBreak"})
            content += _text(line)
        if content:
            nodes.append({"type": "paragraph", "content": content})
    return nodes


def block_to_nodes(block):
    kind = block.get("type")
    if kind == "text":
        return _paragraphs(block.get("text", ""))
    if kind == "heading":
        return [{"type": "heading", "attrs": {"level": block.get("level", 2)}, "content": _text(block.get("text", ""))}]
    if kind == "code":
        nodes = []
        if block.get("filename"):
            nodes.append({"type": "paragraph", "content": [
                {"type": "text", "text": block["filename"], "marks": [{"type": "code"}]}]})
        nodes.append({"type": "codeBlock", "attrs": {"language": block.get("language", "")},
                      "content": _text(block.get("code", ""))})
        return nodes
    if kind == "image" and block.get("src"):
        return [{"type": "image", "attrs": {
            "src": block["src"], "alt": block.get("alt", ""), "title": block.get("caption", "")}}]
    if kind == "note":
        return [{"type": "blockquote", "content": _paragraphs(block.get("text", ""))}]
    return []


def blocks_to_doc(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    for post in Post.objects.all():
        if isinstance(post.body, list):
            content = [node for block in post.body if isinstance(block, dict) for node in block_to_nodes(block)]
            post.body = {"type": "doc", "content": content}
            post.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.JSONField(blank=True, default=apps.blog.content.empty_doc),
        ),
        # Posts written with the earlier block editor become rich text documents.
        migrations.RunPython(blocks_to_doc, migrations.RunPython.noop),
    ]
