# Generated by Django 5.2.17 on 2026-10-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, help_text='Small symbol shown at the top left of the service card (square works best).', upload_to='services/icons/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Write [image 1], [image 2]... on their own line to place the images added below at that spot. Images not mentioned appear after the text.'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/images/')),
                ('alt', models.CharField(blank=True, help_text='Short description for accessibility.', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Image 1 is the lowest number, image 2 the next, and so on.')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
