# Generated by Django 5.2.17 on 2026-10-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, help_text='GitHub repository link (optional).'),
        ),
    ]
